### ISSUE TITLE
Plugin installation ends with an error

### ISSUE THREAD

**Issue by moahmo** [nsftx/vue-cli-plugin-nsoft#38]
When I run `vue add @nsoft/nsoft`, the command has this output at the end:

![image](https://user-images.githubusercontent.com/7250987/60073387-966d3d80-9720-11e9-85f3-e9c8e1162d08.png)

Apparently, it has no functional repercussions.

**Comment by DinkoMiletic** [comment]
@MVucina It looks like https://github.com/nsftx/vue-cli-plugin-nsoft/blob/2b642001c3f9a0a7b4051a4348fc8dba42484952/generator/index.js#L28 is called with wrong type of second argument. See https://cli.vuejs.org/dev-guide/generator-api.html#exitlog.

I am not sure why is hitting error callback.
